### PR TITLE
Expose emblem 0.8.0 options and update emblem version

### PR DESCRIPTION
**Pull request by thec0keman**
0.8.0 is not published to NPM yet, will update here when that is ready

### CODE REVIEW

**Comment by thec0keman** [comment]
0.8 is now published, so this should be good to merge.

**Comment by joebartels** [comment]
💥

**Comment by joebartels** [comment]
sweet. @thec0keman what are your thoughts on bumping ember-cli-emblem to v 0.8.0 so it's in lockstep with emblem?

**Comment by thec0keman** [comment]
Makes a lot of sense!

**Comment by joebartels** [comment]
💥

**Pull request merged**
