### PR TITLE
Fix route and component generators

### PR DESCRIPTION
**Pull request by ntippie**
Fix 'unknown blueprint' error occurring after Ember update. 

Patterned after kimroen/ember-cli-coffeescript#115

#41

### CODE REVIEW

**Comment by joebartels** [comment]
noice

**Comment by joebartels** [comment]
Solved it for a couple projects over here @ntippie 

As to not break lockstep with emblem repo which is still on 0.8.1, we'll call this a beta release

Can you bump the version in package.json to `0.8.2-beta.1` 

I'll merge and publish asap.

**Comment by ntippie** [comment]
There you go! Glad you are enjoying it.

**Comment by alobaidizt** [comment]
Note: be sure to use [#46](https://github.com/Vestorly/ember-cli-emblem/pull/46) commit hash instead of #45 since it corrects route blueprint mistakenly looking up wrong blueprint issue.

**Comment by alobaidizt** [comment]
@ntippie I still get unknown component 😢 running ember-cli 2.7.0 and enabling blueprints for both coffeescrip and emblem.

```
    "ember-cli-coffeescript": "kimroen/ember-cli-coffeescript#ebb4abd237599ae7bd3a852cd71d63924a79851f",
    "ember-cli-emblem": "Vestorly/ember-cli-emblem#2798a2a33ea9cbad6418e5a546756757eb7baa77",
```

**Comment by ntippie** [comment]
@alobaidizt Looks like there is an issue when using both `ember-cli-emblem` and `ember-cli-coffeescript`. See #35

**Comment by alobaidizt** [comment]
@ntippie yeah, I ended up just disabling emblem blueprints in ember's environment file.

**Comment by ralmidani** [comment]
@alobaidizt How exactly do you disable emblem blueprints? I searched all over but could not find an answer.

This sounds better than manually deleting the blueprints folder from the node module.

**Comment by alobaidizt** [comment]
Hey @ralmidani, you can do that by adding this to your environement.js file under `/config`: 
`ENV.emblemOptions {
  blueprints: false
}`

**Pull request merged**
