### PR TITLE
Add emblem blueprints

### PR DESCRIPTION
**Pull request by jsec**
Adds emblem blueprints for templates, routes, and components.

### CODE REVIEW

**Comment by jimmay5469** [comment]
Any way we could make this an option that can be turned off from `config/environment.js` like ember-cli-coffeescript does?  See: https://github.com/kimroen/ember-cli-coffeescript#blueprints.  This would be nice in case you want to allow emblem but default to htmlbars, this is what we do for coffeescript.

In addition, I'm new to ember-cli blueprints so I don't know if this is possible, but it would be nice if you could use the JS parts of the blueprint from the default location instead of duplicating them here.  This way the JS parts of the blueprints wouldn't have to be maintained here, and also you could potentially generate coffeescript files if you wanted that instead of JS.

**Comment by jsec** [comment]
Making it a configurable option seems like a good idea. I'll play around with that tonight.

On your second point, I'm not sure that's possible. In working on this, if I didn't include the JS portions of the blueprint, an ```ember g``` would not generate the JS file at all.

**Comment by jimmay5469** [comment]
Awesome, thanks!

And on the second point: yeah, thats what my experience has been so far as well @jsec.  Didn't know if it was possible and I just didn't know how to do it, or if it was not currently possible.

**Comment by jsec** [comment]
@jimmay5469 there is now an ENV.emblemOptions configuration option that was completely based off of  [ember-cli-coffeescript](https://github.com/kimroen/ember-cli-coffeescript#blueprints). Credit to @kimroen for an outstanding addon.

**Comment by jimmay5469** [comment]
Nice! :+1:

**Comment by kimroen** [comment]
:clap: :clap: :clap:

**Comment by ballPointPenguin** [comment]
One project I'm working on uses emblem and coffee, so it looks like I'd have to choose to generate emblem +js or coffee + hbs. Not a big deal since generated templates are really just placeholders.

**Comment by mixonic** [comment]
@jondayton y'all want to take a look at this? Seems like a fine addition :-)

**Comment by alex88** [comment]
:+1:

**Comment by joebartels** [comment]
@jsec could you rebase and squash these to a single commit and add a line in the readme indicating an `ember generate` command :)

**Comment by jsec** [comment]
Not a problem. Hope to get to this tonight.

**Comment by joebartels** [comment]
awesome thanks!

**Comment by jsec** [comment]
@joebartels commits have been squashed. If there is anything else I need to do, let me know.

Thanks! :)

**Comment by joebartels** [comment]
looks good. thanks for working on this feature @jsec

**Comment by mixonic** [comment]
:fireworks:

**Comment by aliaksandrb** [comment]
:cool:

**Comment by coladarci** [comment]
This was working for me in my last project but I just created a new one w/ Ember CLI `0.2.3` and the blueprints are still generating `.hbs`.
```
ember g route new-route
version: 0.2.3
installing
  create app/routes/new-route.js
  create app/templates/new-route.hbs
installing
  create tests/unit/routes/new-route-test.js
```
Anyone seen and addressed this? Thanks!

**Comment by jsec** [comment]
I don't think the version on npm has been updated yet. See #15.

**Comment by coladarci** [comment]
Thank you!

**Pull request merged**
