### PR TITLE
minor release 0.2.7 to 0.3.0 for emblem 0.6.x support

### PR DESCRIPTION
**Pull request by joebartels**

### CODE REVIEW

**Comment by mmahalwy** [comment]
:+1: 
Thanks @joebartels

**Comment by joebartels** [comment]
thank you!

**Comment by mmahalwy** [comment]
@joebartels any idea when this will get merged in? ;)

**Comment by coladarci** [comment]
Thanks for merging @jondayton - can you publish to npm so we can try it out? Thanks!

**Comment by piotrpalek** [comment]
@jondayton hey, I think you forgot to add the tag to git so people can use this new version

**Comment by jondayton** [comment]
@piotrpalek @mmahalwy @joebartels @coladarci it's tagged and published to npm.

**Comment by piotrpalek** [comment]
thanks :+1:

**Comment by mmahalwy** [comment]
Thank you!

**Pull request merged**
