### PR TITLE
fix: this.ui is undefined

### LINKED ISSUE #25: TypeError: Cannot read property 'writeLine' of undefined
```
jan@ubuntu:~/code/citb/citb-website$ ember v
version: 1.13.1
node: 2.3.0
npm: 2.12.1
jan@ubuntu:~/code/citb/citb-website$ ember g route blog
version: 1.13.1
installing route
  create app/blog/route.js
  create app/blog/template.emblem
Cannot read property 'writeLine' of undefined
TypeError: Cannot read property 'writeLine' of undefined
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli/blueprints/route/index.js:68:14)
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli-emblem/blueprints/route/index.js:35:42)
    at Class.module.exports.afterInstall (/home/jan/code/citb/citb-website/node_modules/ember-cli-emblem/blueprints/route/index.js:35:42)
    at lib$rsvp$$internal$$tryCatch (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/jan/code/citb/citb-website/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

`ember g route` and `ember d route` both fail with this error.

### PR DESCRIPTION
**Pull request by buschtoens**
This is a temporary "hack" that works around https://github.com/ember-cli/ember-cli/issues/2255 for now.

Fixes #25.

### CODE REVIEW

**Comment by joebartels** [comment]
@buschtoens thanks for creating the issue and pinging the ember-cli repo too . I'll repro soon and review the fix you wrote :)

**Comment by buschtoens** [comment]
@joebartels Awesome, thanks! :)

**Comment by jtippett** [comment]
👍for this, right now anyone using ember-cli is having this issue (and ember-cli is all but official)

**Comment by buschtoens** [comment]
@joebartels Could you publish this fix to npm as well? I was just using this command on a fresh app and was stumped that I got that same error again.

**Pull request merged**
