### PR TITLE
Version bump for emblem

### PR DESCRIPTION
**Pull request by mmahalwy**
As per this issue: https://github.com/machty/emblem.js/issues/242#issuecomment-120420798

### CODE REVIEW

**Comment by coladarci** [comment]
:+1:

**Comment by buschtoens** [comment]
:+1:

**Comment by mixonic** [comment]
Should be `0.6.1` and above. `0.6.0` is not a working release.

**Comment by mmahalwy** [comment]
@mixonic bumped it to 0.6.1

**Comment by hwhelchel** [comment]
:+1:

**Comment by joebartels** [comment]
@mmahalwy looks like bringing in emblem `^0.6.1` is breaking change for people using `ember-cli-htmlbars: 0.6.x` ([supporting plugin for handlebars 2.0](https://github.com/ember-cli/ember-cli-htmlbars#handlebars-20-support) ). 
I'll bump ember-cli-emblem version accordingly, probably `1.0.0`. if you're aware of other dependencies that could break from this this version bump -just give heads up :)

**Pull request merged**
